# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SSMClientToolsSetup

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16    
      - name: Install Secure Software Manager client tools
        id: installer
        run: |
         npm ci
         npm start
      - if: matrix.os=='windows-latest'
        shell: bash
        run: |
          cd C:\\Users\\RUNNER~1\\AppData\\Roaming\\GnuPG\
          dir
          cat ~/.gnupg/gpg-agent.conf
          gpg --card-status
          gpgconf --kill all
           gpg-agent --daemon
      - name: Verify installation
        run: |
         cd "${{ steps.installer.outputs.extractPath }}"
         echo "Tools installed are ..."
         dir    
      - if: matrix.os=='ubuntu-latest'
        shell: bash
        run: |
          cat ~/.gnupg/gpg-agent.conf
          gpg --card-status
          gpgconf --kill all
    env:
      SSM_CLIENT_INSTALLER_READ_TOKEN: ${{ secrets.SSM_CLIENT_INSTALLER_READ_TOKEN }}
