# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SSMClientToolsSetup

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install Secure Software Manager client tools
        id: installer
        run: |
         npm ci
         npm start
      - run: |
          cd home//runner
          dir
          gpg --card-status
          gpgconf --kill all
      - name: Verify installation
        run: |
         cd "${{ steps.installer.outputs.extractPath }}"
         echo "Tools installed are ..."
         dir    
      - run: gpg --card-status  
    env:
      SSM_CLIENT_INSTALLER_READ_TOKEN: ${{ secrets.SSM_CLIENT_INSTALLER_READ_TOKEN }}
