# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SSMClientToolsSetup

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest,ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Secure Software Manager client tools
        id: installer
        run: |
         npm ci
         npm start
      - if: matrix.os=='windows-latest'
        run: |
          
          cd C:\\Users\\RUNNER~1\\
          dir
          gpg --card-status
          gpgconf --kill all
      - name: Verify installation
        run: |
         cd "${{ steps.installer.outputs.extractPath }}"
         echo "Tools installed are ..."
         dir    
      - if: matrix.os=='ubuntu-latest'
        shell: bash
        run: |
         if [ -f /usr/lib/systemd/user/gpg-agent.service ]; then
          mkdir ~/.gnupg
          cat <<EOT >> ~/.gnupg/gpg-agent.conf
          allow-preset-passphrase
          default-cache-ttl 60
          max-cache-ttl 50
         EOT
          chmod 600 ~/.gnupg/*
          chmod 700 ~/.gnupg
          systemctl --user restart gpg-agent
         else
          gpg-agent --daemon --allow-preset-passphrase \
          --default-cache-ttl 60 --max-cache-ttl 60
         fi
    env:
      SSM_CLIENT_INSTALLER_READ_TOKEN: ${{ secrets.SSM_CLIENT_INSTALLER_READ_TOKEN }}
