# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SSMClientToolsSetup

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup-gpg
        uses: olafurpg/setup-gpg@v3
    
      - name: Install Secure Software Manager client tools
        id: installer
        run: |
         npm ci
         npm start
      
      - name: Configure and either start or restart GPG agent
        run: |
          if [ -f /usr/lib/systemd/user/gpg-agent.service ]; then
          mkdir ~/.gnupg
          cat <<EOT >> ~/.gnupg/gpg-agent.conf
          verbose 
          debug-all 
          scdaemon-program ${{ steps.installer.outputs.extractPath }} 
           
          EOT
          chmod 600 ~/.gnupg/*
          chmod 700 ~/.gnupg
          systemctl --user restart gpg-agent
      - name: Verify installation
        run: |
         cd "${{ steps.installer.outputs.extractPath }}"
         echo "Tools installed are ..."
         dir      
    env:
      SSM_CLIENT_INSTALLER_READ_TOKEN: ${{ secrets.SSM_CLIENT_INSTALLER_READ_TOKEN }}
