# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SSMClientToolsSetup

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Client tools installation
        id: installer
        run: |
         npm ci
         npm start
      - if: matrix.os=='windows-latest'   
        name: verify installation
        run: |
         cd "${{ steps.installer.outputs.directoryPath }}"
         echo "Tools installed are ..."
         dir
      - if: matrix.os=='ubuntu-latest'   
        name: verify installation
        run: |
         cd "${{ steps.installer.outputs.directoryPath }}"
         echo "Tools installed are ..."
         dir      
    env:
      SSM_CLIENT_INSTALLER_READ_TOKEN: ${{ secrets.SSM_CLIENT_INSTALLER_READ_TOKEN }}
